baseURL = 'https://gtcode.com/'
languageCode = 'en-us'
title = 'GTCode | Paul E. Lowndes'
theme = 'minimal'
disableKinds = ['taxonomy', 'term']
canonifyURLs = true

[params]
  description = 'Paul E. Lowndes is an AI engineering consultant in Oahu, Hawaii, who also leads investigative journalism initiatives and Chiral Narrative Synthesis research at GTCode.com.'
  author = 'Paul E. Lowndes'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[minify]
  minifyOutput = true

[minify.tdewolff.html]
  keepComments = true
  keepConditionalComments = true
